### ISSUE TITLE
DirectClient removal from SecurityHandler is not concurrent-safe

### ISSUE THREAD

**Issue by mwm-twx** [pac4j/vertx-pac4j#126]
Pac4J version: 3.4.0
Vertx version: 3.8.0 (also occurs on 3.6.3)
Vertx-pac4j version: 4.1.0

The code added in https://github.com/pac4j/vertx-pac4j/issues/93 to strip `DirectClient` implementations generates exceptions for concurrent requests through multiple event-loops for a single user.

`LinkedHashMap` is not a concurrent `Map` and is modified (`clear` and `putAll`) while being iterated through the Java 8 streams framework.

The specific exception encountered is:
```
java.lang.IllegalStateException: Duplicate key ...
       at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
       at java.util.HashMap.merge(HashMap.java:1254)
       at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
       at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
       at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
       at java.util.Iterator.forEachRemaining(Iterator.java:116)
       at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
       at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
       at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
       at org.pac4j.vertx.handler.impl.SecurityHandler.handle(SecurityHandler.java:94)
       at org.pac4j.vertx.handler.impl.SecurityHandler.handle(SecurityHandler.java:34)
```

Note that a potential quick-fix of using the `BinaryOperator` version of `toMap` to handle the duplicate keys leads to a different exception:
```
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
```

**Comment by leleuj** [comment]
Did you find some good solution on this?

**Comment by mwm-twx** [comment]
Not really.  We didn't need to have anonymous profiles, so we made a custom `SecurityHandler` which removes the additions from the linked issue.

**Comment by leleuj** [comment]
OK. I'll rework that when upgrading to pac4j v4.

**Comment by leleuj** [comment]
@mwm-twx I have strongly refactored the vertx-pac4j library and removed the strip out of the `DirectClient`s: can you try with the version 5.0.0-SNAPSHOT (and pac4j v4.0.2)? Thx

**Comment by mwm-twx** [comment]
The issue appears to be gone, thanks!
