### ISSUE TITLE
When using vertx-pac4j 2.0.2 with the latest vertx version and pac4j 1.9.1 (1.9.2 same result)

### ISSUE THREAD

**Issue by BerndSerker** [pac4j/vertx-pac4j#77]
SCHWERWIEGEND: org/pac4j/core/client/ClientFinder
java.lang.NoClassDefFoundError: org/pac4j/core/client/ClientFinder
	at com.codeclusion.robin.textanalysisplatform.web.TAPUI.start(TAPUI.java:172)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.DeploymentManager$$Lambda$31/202125197.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$27/2125257614.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.pac4j.core.client.ClientFinder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

**Comment by millross** [comment]
pac4j 1.9.x is not supported by vertx-pac4j 2.0.x

**Comment by millross** [comment]
We are still porting vertx-pac4j to support the changes for pac4j 1.9. Unfortunately I have less time to devote to this than I would like. 

The 2.1.0 Snapshot should work with 1.9.1 and 1.9.2 if you don't use the latest features such as multiprofile.

**Comment by millross** [comment]
Also please note that pac4j 1.9.x is NOT binary compatible with 1.8.x. Going from 1.8 to 1.9 broke several API compatibilities. Up until pac4j 2.0, a minor version change is not backward compatible.

**Comment by millross** [comment]
2.1.0-SNAPSHOT now updated to use pac4j 1.9.4, with all tests passing. So if you want to use 1.9 then I'd recommend snapshot as long as you don't need to be production-ready yet. In addition as a note multi profile support is now there for indirect clients, but not yet for direct clients (direct client multi profile support in vertx-pac4j is the next priority).

**Comment by millross** [comment]
Also note 1.9.4 fixes a security vulnerability introduced in 1.9.2 (see google groups for pac4j for details) so regardless of anything else you should use 1.9.4 rather than 1.9.2.
